# Generated by Django 5.1.4 on 2025-01-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="pages",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
