# Generated by Django 5.1.4 on 2025-01-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
