# Generated by Django 5.1.4 on 2025-01-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_is_published_post_posted_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="is_published",
            new_name="status",
        ),
    ]
