# Generated by Django 5.1.4 on 2025-01-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/%Y/%m/%d/"),
        ),
    ]
