# Generated by Django 5.1.4 on 2025-02-22 08:34

from django.db import migrations, models
from django.utils.text import slugify

def create_slug(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    for post in Post.objects.all():
        base_slug = slugify(post.title)
        slug = base_slug
        counter = 1
        # Sprawdzamy, czy slug już istnieje
        while Post.objects.filter(slug=slug).exists():
            # Jeśli tak, dodajemy licznik na końcu
            slug = f"{base_slug}-{counter}"
            counter += 1
        post.slug = slug
        post.save()

class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(
            create_slug,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=False, max_length=255, unique=True),
        ),
    ]
