# Generated by Django 5.1.5 on 2025-02-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0004_book"),
    ]

    operations = [

        migrations.RunSQL(
            """
            CREATE VIEW book_summary AS
            SELECT examples_book.id, examples_book.title, examples_author.name AS author_name, examples_book.price
            FROM examples_book
            JOIN examples_author ON examples_book.author_id = examples_author.id;
            """,
            reverse_sql="DROP VIEW IF EXISTS book_summary;"
        ),

    ]
